#!/usr/bin/env bash
# install-git-hook.sh — Opt-in installer for Obsidian vault commit capture post-commit hook.
#
# Provides safe, idempotent installation, status reporting, uninstallation,
# and non-blocking post-commit execution with legacy hook chaining.
#
# Usage:
#   install-git-hook.sh {render|install|status|uninstall} [target_path] [--scope local|global]

set -euo pipefail

MARKER="# obsidian-commit-capture-hook"
LEGACY_NAME="post-commit.legacy"

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd -P)"
DEFAULT_COMMIT_META="${SCRIPT_DIR}/commit-meta.sh"
DEFAULT_KEEPER="${SCRIPT_DIR}/keeper"

usage() {
  echo "usage: install-git-hook.sh {render|install|status|uninstall} [target_path] [--scope local|global]" >&2
  exit 2
}

resolve_hooks_dir() {
  local target_path="$1" scope="$2"
  if [ "$scope" = "global" ]; then
    local global_hooks
    global_hooks="$(git config --global core.hooksPath 2>/dev/null || true)"
    if [ -z "$global_hooks" ]; then
      global_hooks="${HOME}/.config/git/hooks"
    fi
    printf '%s\n' "$global_hooks"
  else
    local repo_dir="${target_path:-$PWD}"
    if [ -f "$repo_dir" ]; then
      repo_dir="$(dirname -- "$repo_dir")"
    fi
    local common_dir
    common_dir="$(git -C "$repo_dir" rev-parse --path-format=absolute --git-common-dir 2>/dev/null)" || {
      common_dir="$(git -C "$repo_dir" rev-parse --git-common-dir 2>/dev/null)" || {
        echo "install-git-hook: not a git repository: $repo_dir" >&2
        return 1
      }
    }
    if [ "${common_dir#/}" = "$common_dir" ]; then
      common_dir="$(cd -- "$repo_dir" && pwd -P)/${common_dir}"
    fi
    printf '%s\n' "${common_dir}/hooks"
  fi
}

render_hook() {
  local meta_bin="${1:-$DEFAULT_COMMIT_META}"
  local keeper_bin="${2:-$DEFAULT_KEEPER}"
  cat <<EOF
#!/usr/bin/env bash
${MARKER}
# Managed post-commit hook for Obsidian vault commit capture.
# Automatically generated by install-git-hook.sh.

set +e

HOOK_DIR="\$(cd -- "\$(dirname -- "\$0")" && pwd -P)"
META_BIN="\${OBSIDIAN_COMMIT_META_BIN:-${meta_bin}}"
KEEPER_BIN="\${OBSIDIAN_KEEPER_BIN:-${keeper_bin}}"

if [ ! -f "\$META_BIN" ] && command -v commit-meta.sh >/dev/null 2>&1; then
  META_BIN="\$(command -v commit-meta.sh)"
fi
if [ ! -f "\$KEEPER_BIN" ] && command -v keeper >/dev/null 2>&1; then
  KEEPER_BIN="\$(command -v keeper)"
fi

if [ -f "\$META_BIN" ]; then
  RECORD="\$( "\$META_BIN" HEAD 2>/dev/null || true )"
  if [ -n "\$RECORD" ] && [ -f "\$KEEPER_BIN" ]; then
    get_field() {
      local rec="\$1" f="\$2="
      printf '%s\n' "\$rec" | awk -v prefix="\$f" '
        {
          idx = index(\$0, prefix)
          if (idx > 0) {
            rest = substr(\$0, idx + length(prefix))
            p = index(rest, " | ")
            if (p > 0) {
              print substr(rest, 1, p - 1)
            } else {
              print rest
            }
          }
        }
      '
    }

    hash="\$(get_field "\$RECORD" "hash")"
    branch="\$(get_field "\$RECORD" "branch")"
    files="\$(get_field "\$RECORD" "files")"
    org_repo="\$(get_field "\$RECORD" "org_repo")"
    repo_name="\$(get_field "\$RECORD" "repo_name")"
    date="\$(get_field "\$RECORD" "date")"
    time="\$(get_field "\$RECORD" "time")"
    vault_path="\$(get_field "\$RECORD" "vault_path")"
    msg="\$(get_field "\$RECORD" "msg")"

    if [ -n "\$vault_path" ] && [ -d "\$vault_path" ] && [ -n "\$hash" ] && [ -n "\$org_repo" ]; then
      TMP_DIR="\$(mktemp -d "\${TMPDIR:-/tmp}/git-hook-keeper.XXXXXX" 2>/dev/null || true)"
      if [ -n "\$TMP_DIR" ] && [ -d "\$TMP_DIR" ]; then
        BODY_FILE="\${TMP_DIR}/body.md"
        INIT_FILE="\${TMP_DIR}/init.md"
        TARGET="Projects/Development/\${org_repo}/\${date}.md"
        SECTION="## \${time} - \${hash}"

        cat <<BODY_EOF > "\$BODY_FILE"
**Branch:** \${branch}
**Message:** \${msg}
**Files:** \${files}

---
BODY_EOF

        cat <<INIT_EOF > "\$INIT_FILE"
---
date: \${date}
repo: \${org_repo}
tags: [\${repo_name}, auto-captured]
source: git-hook
---

# \${repo_name} - \${date}
INIT_EOF

        "\$KEEPER_BIN" append \\
          --vault "\$vault_path" \\
          --target "\$TARGET" \\
          --section "\$SECTION" \\
          --body-file "\$BODY_FILE" \\
          --init-file "\$INIT_FILE" \\
          --skip-if-hash "\$hash" >/dev/null 2>&1 || true

        rm -rf "\$TMP_DIR" >/dev/null 2>&1 || true
      fi
    fi
  fi
fi

LEGACY_HOOK="\${HOOK_DIR}/${LEGACY_NAME}"
if [ -x "\$LEGACY_HOOK" ]; then
  "\$LEGACY_HOOK" "\$@" || true
elif [ -f "\$LEGACY_HOOK" ]; then
  /bin/bash "\$LEGACY_HOOK" "\$@" || true
fi

exit 0
EOF
}

cmd_render() {
  local meta_bin="${1:-}"
  local keeper_bin="${2:-}"
  render_hook "$meta_bin" "$keeper_bin"
}

cmd_status() {
  local target_path="$1" scope="$2"
  local hooks_dir
  hooks_dir="$(resolve_hooks_dir "$target_path" "$scope")" || return 1

  local hook_file="${hooks_dir}/post-commit"
  local legacy_file="${hooks_dir}/${LEGACY_NAME}"

  if [ ! -f "$hook_file" ]; then
    echo "not-installed"
    return 1
  fi

  if grep -qF "$MARKER" "$hook_file" 2>/dev/null; then
    if [ -f "$legacy_file" ]; then
      echo "installed (chained legacy hook active)"
    else
      echo "installed"
    fi
    return 0
  else
    echo "foreign-hook-detected"
    return 2
  fi
}

cmd_install() {
  local target_path="$1" scope="$2"
  local hooks_dir
  hooks_dir="$(resolve_hooks_dir "$target_path" "$scope")" || return 1

  mkdir -p "$hooks_dir"
  local hook_file="${hooks_dir}/post-commit"
  local legacy_file="${hooks_dir}/${LEGACY_NAME}"

  if [ -f "$hook_file" ] && ! grep -qF "$MARKER" "$hook_file" 2>/dev/null; then
    if [ -f "$legacy_file" ]; then
      echo "install-git-hook: error: collision detected — both post-commit and post-commit.legacy exist" >&2
      return 1
    fi
    mv "$hook_file" "$legacy_file"
    echo "install-git-hook: preserved existing post-commit hook to ${legacy_file}" >&2
  fi

  render_hook "$DEFAULT_COMMIT_META" "$DEFAULT_KEEPER" > "$hook_file"
  chmod +x "$hook_file"

  if [ "$scope" = "global" ]; then
    local current_global
    current_global="$(git config --global core.hooksPath 2>/dev/null || true)"
    if [ "$current_global" != "$hooks_dir" ]; then
      git config --global core.hooksPath "$hooks_dir"
      echo "install-git-hook: set git config --global core.hooksPath to ${hooks_dir}" >&2
    fi
  fi

  echo "installed"
}

cmd_uninstall() {
  local target_path="$1" scope="$2"
  local hooks_dir
  hooks_dir="$(resolve_hooks_dir "$target_path" "$scope")" || return 1

  local hook_file="${hooks_dir}/post-commit"
  local legacy_file="${hooks_dir}/${LEGACY_NAME}"

  if [ ! -f "$hook_file" ]; then
    echo "not-installed"
    return 0
  fi

  if ! grep -qF "$MARKER" "$hook_file" 2>/dev/null; then
    if [ ! -f "$legacy_file" ]; then
      echo "not-installed"
      return 0
    else
      echo "skipped (foreign hook active)" >&2
      return 1
    fi
  fi

  rm -f "$hook_file"

  if [ -f "$legacy_file" ]; then
    mv "$legacy_file" "$hook_file"
    chmod +x "$hook_file" 2>/dev/null || true
    echo "install-git-hook: restored preserved legacy hook from ${legacy_file}" >&2
  fi

  if [ "$scope" = "global" ]; then
    local current_global
    current_global="$(git config --global core.hooksPath 2>/dev/null || true)"
    if [ "$current_global" = "$hooks_dir" ]; then
      git config --global --unset core.hooksPath 2>/dev/null || true
      echo "install-git-hook: unset git config --global core.hooksPath" >&2
    fi
  fi

  echo "uninstalled"
}

main() {
  [ $# -ge 1 ] || usage

  local command="$1"
  shift

  local args=()
  local scope="local"

  while [ $# -gt 0 ]; do
    case "$1" in
      --scope)
        [ $# -ge 2 ] || usage
        scope="$2"
        shift 2
        ;;
      --scope=*)
        scope="${1#*=}"
        shift
        ;;
      -h|--help)
        usage
        ;;
      *)
        args+=("$1")
        shift
        ;;
    esac
  done

  local target_arg="${args[0]:-}"
  local second_arg="${args[1]:-}"

  case "$command" in
    render)
      cmd_render "$target_arg" "$second_arg"
      ;;
    status)
      cmd_status "$target_arg" "$scope"
      ;;
    install)
      cmd_install "$target_arg" "$scope"
      ;;
    uninstall)
      cmd_uninstall "$target_arg" "$scope"
      ;;
    *)
      usage
      ;;
  esac
}

main "$@"
